#ifndef MESSAGETYPE_H
#define MESSAGETYPE_H

enum class MessageType
{
    //登陆注册信息
    LOGIN,REGISTER,CHANGE_PASSWORD, DISCONNECT, EDIT_USER_INFO,

    //用户对好友的操作
    ADD_FRIEND,DELETE_FRIEND,ADD_GROUP,DELETE_GROUP, REQUEST_FRIEND_INFO, REQUEST_GROUP_INFO,

    //用户发送信息
    CS_USER_INFO,CS_RECORD,CS_TEXT,CS_PICTURE,CS_EMOT,

    //用户接受信息
    SC_USER_INFO,SC_RECORD,SC_TEXT,SC_PICTURE,SC_EMOT, SC_GROUP_INFO, SC_GROUPMEMBERS_INFO,

    //群聊信息
    EDIT_GROUPO_INFO,CREATE_GROUP,DISMISS_GROUP,QUIT_GROUP,JOIN_GROUP,

    VOICE
};




#endif // MESSAGETYPE_H
